# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAViewParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_organization', models.CharField(blank=True, choices=[('Admins, Inc.', 'Admins, Inc.'), ('Candy Shop', 'Candy Shop'), ('IBM', 'IBM')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ldaviewparameters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
