# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0003_auto_20170903_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldaviewparameters',
            name='organization',
            field=models.CharField(choices=[('Admins, Inc.', 'Admins, Inc.'), ('Candy Shop', 'Candy Shop'), ('IBM', 'IBM')], max_length=30),
        ),
    ]
